
function DICOMAT_Series_Selection_GUI(parent_GUI_handle, new_GUI_position, listbox_entries, listbox_selection_idx)

GUI_color = get(0,'defaultUicontrolBackgroundColor');

% Create GUI figure
fig = figure('Toolbar', 'none', 'Units', 'normalized', ...
						 'position', new_GUI_position, 'Color', GUI_color, ...
						 'Name', '', 'MenuBar', 'none', 'NumberTitle', 'off');
						
set(fig, 'CloseRequestFcn', {@reactivate_parent_GUI, parent_GUI_handle, fig});

% Set the Tag for this GUI and prefix with the parent GUI name to enable easy deletion
set_tag_for_GUI_child(fig, parent_GUI_handle, 'Series Selection GUI');

% Create outer panel handle - decorative
outer_panel_gap = 0.02; outer_panel_y_offset = 0.1; 
outer_panel_pos = [outer_panel_gap outer_panel_y_offset (1-2*outer_panel_gap) (1-outer_panel_y_offset-outer_panel_gap)];

outer_panel_handle = uipanel('Parent', fig, 'Title', 'Select Series', ...
											 			 'BackgroundColor', GUI_color, ...
											 			 'Units', 'normalized', 'Position', outer_panel_pos);

% Create inner panel handle - which will be the parent for the listbox
inner_panel_gap = 0.02; inner_panel_y_offset = inner_panel_gap;
inner_panel_pos = [inner_panel_gap inner_panel_y_offset (1-2*inner_panel_gap) (1-inner_panel_y_offset-inner_panel_gap)];

inner_panel_handle = uipanel('Parent', outer_panel_handle, ...
											 			 'BackgroundColor', GUI_color, ...
											 			 'BorderType', 'none', ...
											 			 'Units', 'normalized', 'Position', inner_panel_pos);

% Predefined series filters
predefined_series_filters = {'Oxford Clinical DCE Sequence', ...
														'Oxford Clinical VFA Sequence', ...
														'Oxford Avastin DCE Sequence', ...
														'Oxford Avastin VFA Sequence', ...
														'Oxford Avastin BOLD Sequence', ...
														'Oxford Avastin DWI Sequence', ...
														'MVH Avastin DCE Sequence', ...
														'MVH Avastin VFA Sequence', ...
														'MVH Avastin BOLD Sequence', ...
														'MVH Avastin DWI Sequence'};

% Create series selection listbox
listbox = Create_Listbox_Selection_UI(inner_panel_handle, listbox_entries, listbox_selection_idx, [], ...
																	 predefined_series_filters, @DICOMAT_Predefined_Series_Selection_Filters);

% Setup ok and cancel buttons
uicontrol('style', 'pushbutton', 'String', 'OK', ...
				  'Fontunits', 'normalized', 'Fontsize', 0.4, ...
					'Units', 'normalized', 'Position', [0.3 0.03 0.1 0.05], ...
					'Parent', fig, 'callback', {@DICOMAT_Validate_Series_Selection, parent_GUI_handle, fig, listbox});

uicontrol('style', 'pushbutton', 'String', 'Cancel', ...
					'Fontunits', 'normalized', 'Fontsize', 0.4, ...
					'Units', 'normalized', 'Position', [0.6 0.03 0.1 0.05], ...
          'Parent', fig, 'callback', {@reactivate_parent_GUI, parent_GUI_handle, fig});

% Make parent GUI invisible
set(parent_GUI_handle, 'Visible', 'off');
